#ifndef COINALGEBRA_CONFIG_H
#define COINALGEBRA_CONFIG_H

#define COINALGEBRA_VERSION_MAJOR 0
#define COINALGEBRA_VERSION_MINOR 1
#define COINALGEBRA_VERSION_PATCH 0

#define COINALGEBRA_VERSION "0.1.0"

#endif
